const KEY_CODES = [
  { name: "Backquote", value: ["`", "~", "ё", "Ё"], class: [""] },
  { name: "Digit1", value: [1, "!", "1", "!"], class: [""] },
  { name: "Digit2", value: [2, "@", "2", '"'], class: [""] },
  { name: "Digit3", value: [3, "#", "3", "№"], class: [""] },
  { name: "Digit4", value: [4, "$", "4", ";"], class: [""] },
  { name: "Digit5", value: [5, "%", "5", "%"], class: [""] },
  { name: "Digit6", value: [6, "^", "6", ":"], class: [""] },
  { name: "Digit7", value: [7, "&", "7", "?"], class: [""] },
  { name: "Digit8", value: [8, "*", "8", "*"], class: [""] },
  { name: "Digit9", value: [9, "(", "9", "("], class: [""] },
  { name: "Digit0", value: [0, ")", "0", ")"], class: [""] },
  {
    name: "Backspace",
    value: ["Backspace", "Backspace", "Backspace", "Backspace"],
    class: ["dark long"],
  },
  { name: "Tab", value: ["Tab", "Tab", "Tab", "Tab"], class: ["dark"] },
  { name: "KeyQ", value: ["q", "Q", "й", "Й"], class: [""] },
  { name: "KeyW", value: ["w", "W", "ц", "Ц"], class: [""] },
  { name: "KeyE", value: ["e", "E", "у", "У"], class: [""] },
  { name: "KeyR", value: ["r", "R", "к", "К"], class: [""] },
  { name: "KeyT", value: ["t", "T", "е", "Е"], class: [""] },
  { name: "KeyY", value: ["y", "Y", "н", "Н"], class: [""] },
  { name: "KeyU", value: ["u", "U", "г", "Г"], class: [""] },
  { name: "KeyI", value: ["i", "I", "ш", "Ш"], class: [""] },
  { name: "KeyO", value: ["o", "O", "щ", "Щ"], class: [""] },
  { name: "KeyP", value: ["p", "P", "з", "З"], class: [""] },
  { name: "Delete", value: ["Del", "Del", "Del", "Del"], class: ["dark"] },
  {
    name: "CapsLock",
    value: ["CapsLock", "CapsLock", "CapsLock", "CapsLock"],
    class: ["dark long"],
  },
  { name: "KeyA", value: ["a", "A", "ф", "Ф"], class: [""] },
  { name: "KeyS", value: ["s", "S", "ы", "Ы"], class: [""] },
  { name: "KeyD", value: ["d", "D", "в", "В"], class: [""] },
  { name: "KeyF", value: ["f", "F", "а", "А"], class: [""] },
  { name: "KeyG", value: ["g", "G", "п", "П"], class: [""] },
  { name: "KeyH", value: ["h", "H", "р", "Р"], class: [""] },
  { name: "KeyJ", value: ["j", "J", "о", "О"], class: [""] },
  { name: "KeyK", value: ["k", "K", "л", "Л"], class: [""] },
  { name: "KeyL", value: ["l", "L", "д", "Д"], class: [""] },
  {
    name: "Enter",
    value: ["Enter", "Enter", "Enter", "Enter"],
    class: ["dark long"],
  },
  {
    name: "ShiftLeft",
    value: ["Shift", "Shift", "Shift", "Shift"],
    class: ["dark long"],
  },
  { name: "KeyZ", value: ["z", "Z", "я", "Я"], class: [""] },
  { name: "KeyX", value: ["x", "X", "ч", "Ч"], class: [""] },
  { name: "KeyC", value: ["c", "C", "с", "С"], class: [""] },
  { name: "KeyV", value: ["v", "V", "м", "М"], class: [""] },
  { name: "KeyB", value: ["b", "B", "и", "И"], class: [""] },
  { name: "KeyN", value: ["n", "N", "т", "Т"], class: [""] },
  { name: "KeyM", value: ["m", "M", "ь", "Ь"], class: [""] },
  { name: "Comma", value: [",", "<", "б", "Б"], class: [""] },
  { name: "Period", value: [".", ">", "ю", "Ю"], class: [""] },
  { name: "ArrowUp", value: ["▲", "▲", "▲", "▲"], class: ["dark"] },
  {
    name: "ShiftRight",
    value: ["Shift", "Shift", "Shift", "Shift"],
    class: ["dark long"],
  },
  {
    name: "ControlLeft",
    value: ["Ctrl", "Ctrl", "Ctrl", "Ctrl"],
    class: ["dark"],
  },
  { name: "AltLeft", value: ["Alt", "Alt", "Alt", "Alt"], class: ["dark"] },
  { name: "Space", value: ["", "", "", ""], class: ["logest"] },
  { name: "AltRight", value: ["Alt", "Alt", "Alt", "Alt"], class: ["dark"] },
  {
  name: "ControlRight",
  value: ["Ctrl", "Ctrl", "Ctrl", "Ctrl"],
  class: ["dark"],
  },
  { name: "ArrowLeft", value: ["◄", "◄", "◄", "◄"], class: ["dark"] },
  { name: "ArrowDown", value: ["▼", "▼", "▼", "▼"], class: ["dark"] },
  { name: "ArrowRight", value: ["►", "►", "►", "►"], class: ["dark"] },
];

export default KEY_CODES